In [94]:
import pandas as pd
from mlxtend.preprocessing.transactionencoder import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [95]:
pd.set_option("display.max_rows",500)

In [96]:
df=pd.read_csv("Groceries_dataset.csv")
df.head(10)

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk
5           4941  14-02-2015        rolls/buns
6           4501  08-05-2015  other vegetables
7           3803  23-12-2015        pot plants
8           2762  20-03-2015        whole milk
9           4119  12-02-2015    tropical fruit

In [ ]:
gp=df.groupby(["itemDescription"]).agg({"itemDescription":"count"})
gp.rename(columns={"itemDescription": "CountOfItemDescription"}, inplace=True)
gp.sort_values(by="CountOfItemDescription",ascending=False)

In [98]:
d:dict[int:list]={}
for _,row in df.iterrows():
    key = row[0] 
    value = row[2]
    if key not in d:
        d[key] = []
    d[key].append(value)
market=[]
for i in d.values():
    market.append(i)
del d
market

C:\Users\mitad\AppData\Local\Temp\ipykernel_3392\332444031.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  key = row[0]
C:\Users\mitad\AppData\Local\Temp\ipykernel_3392\332444031.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  value = row[2]

[['tropical fruit',
  'long life bakery product',
  'meat',
  'sugar',
  'rolls/buns',
  'semi-finished bread',
  'whole milk',
  'citrus fruit',
  'candy',
  'napkins'],
 ['whole milk',
  'butter',
  'female sanitary products',
  'pot plants',
  'other vegetables',
  'tropical fruit',
  'root vegetables',
  'whole milk',
  'shopping bags',
  'chocolate',
  'chocolate',
  'coffee',
  'hygiene articles'],
 ['pip fruit',
  'sausage',
  'frankfurter',
  'pork',
  'other vegetables',
  'white wine',
  'long life bakery product',
  'fruit/vegetable juice',
  'flour',
  'hygiene articles'],
 ['other vegetables',
  'soda',
  'citrus fruit',
  'onions',
  'soda',
  'domestic eggs',
  'shopping bags'],
 ['whole milk', 'cling film/bags', 'other vegetables', 'ham', 'white bread'],
 ['rolls/buns',
  'rolls/buns',
  'canned beer',
  'bottled beer',
  'ham',
  'coffee',
  'whole milk',
  'liquor',
  'yogurt',
  'white wine',
  'meat',
  'citrus fruit',
  'hamburger meat',
  'pickled vegetables',
  'salty snack',
  'domestic eggs',
  'soda',
  'canned beer',
  'newspapers',
  'pasta',
  'soda',
  'butter milk',
  'white bread',
  'soda',
  'fruit/vegetable juice',
  'chocolate marshmallow'],
 ['other vegetables',
  'other vegetables',
  'butter milk',
  'tropical fruit',
  'brown bread',
  'chicken',
  'bottled water',
  'pork',
  'berries',
  'soda',
  'processed cheese',
  'dessert',
  'shopping bags'],
 ['pot plants',
  'dessert',
  'root vegetables',
  'sausage',
  'chicken',
  'fruit/vegetable juice',
  'chicken',
  'butter',
  'citrus fruit',
  'tropical fruit',
  'berries',
  'pip fruit',
  'vinegar',
  'newspapers',
  'other vegetables',
  'skin care',
  'chewing gum',
  'whipped/sour cream',
  'rolls/buns'],
 ['whole milk',
  'decalcifier',
  'dessert',
  'pastry',
  'specialty bar',
  'whole milk',
  'beef',
  'red/blush wine',
  'newspapers'],
 ['tropical fruit',
  'whole milk',
  'beef',
  'cream cheese ',
  'citrus fruit',
  'onions',
  'whole milk',
  'frozen vegetables',
  'soda'],
 ['citrus fruit',
  'whole milk',
  'whipped/sour cream',
  'root vegetables',
  'whole milk',
  'mustard',
  'rolls/buns',
  'whole milk',
  'brown bread',
  'whole milk',
  'pot plants',
  'flour',
  'rolls/buns',
  'pastry'],
 ['beef',
  'root vegetables',
  'hamburger meat',
  'pastry',
  'citrus fruit',
  'bottled beer',
  'onions',
  'root vegetables',
  'whole milk',
  'beef',
  'specialty bar',
  'pip fruit',
  'specialty chocolate',
  'cream cheese ',
  'soda',
  'liquor (appetizer)',
  'whole milk',
  'yogurt',
  'waffles',
  'chocolate',
  'bottled beer',
  'dessert',
  'pastry',
  'cling film/bags',
  'candy',
  'sliced cheese',
  'whole milk'],
 ['frankfurter',
  'frankfurter',
  'citrus fruit',
  'cleaner',
  'ham',
  'soda',
  'berries',
  'canned beer',
  'bottled water',
  'pip fruit',
  'pip fruit',
  'newspapers',
  'white bread',
  'processed cheese',
  'pastry',
  'bottled beer',
  'shopping bags',
  'beverages',
  'pickled vegetables',
  'brown bread',
  'soda'],
 ['chicken',
  'beef',
  'tropical fruit',
  'oil',
  'other vegetables',
  'waffles',
  'pip fruit',
  'whipped/sour cream',
  'margarine',
  'pickled vegetables',
  'brown bread'],
 ['butter',
  'beef',
  'other vegetables',
  'pastry',
  'other vegetables',
  'soda',
  'onions',
  'yogurt',
  'seasonal products',
  'curd',
  'UHT-milk'],
 ['fruit/vegetable juice',
  'citrus fruit',
  'pastry',
  'whole milk',
  'tropical fruit',
  'hamburger meat',
  'root vegetables',
  'pip fruit',
  'pastry',
  'soft cheese',
  'other vegetables',
  'root vegetables',
  'yogurt',
  'semi-finished bread',
  'specialty chocolate',
  'softener',
  'rolls/buns',
  'pot plants',
  'bottled water'],
 ['packaged fruit/vegetables',
  'fish',
  'frozen meals',
  'specialty chocolate',
  'brown bread'],
 ['chocolate',
  'sausage',
  'abrasive cleaner',
  'candy',
  'frankfurter',
  'sausage',
  'bottled beer',
  'pastry',
  'citrus fruit',
  'yogurt',
  'whole milk',
  'whole milk',
  'other vegetables',
  'margarine',
  'frozen vegetables',
  'shopping bags',
  'rolls/buns',
  'long life bakery product',
  'other vegetables',
  'canned vegetables',
  'UHT-milk'],
 ['specialty bar',
  'sausage',
  'yogurt',
  'whipped/sour cream',
  'napkins',
  'bottled beer',
  'other vegetables',
  'sparkling wine',
  'bottled beer',
  'chocolate'],
 ['other vegetables',
  'fruit/vegetable juice',
  'sugar',
  'soda',
  'ham',
  'tropical fruit',
  'sausage',
  'photo/film',
  'cat food',
  'seasonal products',
  'seasonal products',
  'sausage',
  'other vegetables',
  'onions',
  'whole milk',
  'butter',
  'domestic eggs',
  'cream cheese ',
  'butter',
  'soups',
  'candy',
  'chewing gum',
  'shopping bags',
  'seasonal products',
  'cream cheese ',
  'yogurt'],
 ['butter milk',
  'frankfurter',
  'sausage',
  'root vegetables',
  'meat',
  'sausage',
  'root vegetables',
  'curd',
  'pip fruit',
  'citrus fruit',
  'butter',
  'soda',
  'frozen meals',
  'frozen meals',
  'whipped/sour cream',
  'salty snack',
  'long life bakery product'],
 ['whole milk',
  'chicken',
  'butter',
  'turkey',
  'bottled water',
  'soft cheese',
  'other vegetables',
  'chicken',
  'bottled water',
  'shopping bags',
  'other vegetables',
  'citrus fruit',
  'canned beer',
  'salty snack',
  'canned vegetables'],
 ['tropical fruit',
  'sausage',
  'pork',
  'hamburger meat',
  'rolls/buns',
  'white bread',
  'coffee',
  'sauces',
  'yogurt',
  'sliced cheese',
  'butter',
  'rolls/buns',
  'coffee',
  'whipped/sour cream'],
 ['tropical fruit',
  'whole milk',
  'yogurt',
  'meat',
  'other vegetables',
  'hard cheese',
  'berries',
  'domestic eggs',
  'baking powder'],
 ['bottled water',
  'misc. beverages',
  'frankfurter',
  'tropical fruit',
  'pastry',
  'liquor',
  'specialty chocolate'],
 ['yogurt',
  'tropical fruit',
  'packaged fruit/vegetables',
  'chicken',
  'soda',
  'rolls/buns',
  'tropical fruit',
  'liquor',
  'root vegetables',
  'herbs',
  'chewing gum',
  'domestic eggs',
  'cream cheese ',
  'salty snack',
  'soda',
  'yogurt'],
 ['sausage',
  'chicken',
  'domestic eggs',
  'curd',
  'cake bar',
  'pastry',
  'whipped/sour cream'],
 ['other vegetables',
  'curd',
  'canned beer',
  'salty snack',
  'domestic eggs',
  'syrup',
  'rolls/buns',
  'hygiene articles',
  'newspapers',
  'cat food',
  'oil'],
 ['brown bread',
  'other vegetables',
  'other vegetables',
  'whole milk',
  'meat',
  'spread cheese',
  'citrus fruit',
  'photo/film',
  'butter',
  'canned beer',
  'rolls/buns',
  'yogurt',
  'fruit/vegetable juice'],
 ['yogurt', 'rolls/buns', 'fruit/vegetable juice', 'spices', 'canned fish'],
 ['hamburger meat',
  'bottled beer',
  'cling film/bags',
  'sausage',
  'rolls/buns',
  'beef',
  'other vegetables',
  'other vegetables',
  'bottled beer',
  'curd',
  'whipped/sour cream',
  'yogurt',
  'chewing gum',
  'whole milk',
  'rice',
  'UHT-milk',
  'other vegetables',
  'specialty fat',
  'chocolate',
  'coffee',
  'kitchen towels'],
 ['root vegetables',
  'berries',
  'frankfurter',
  'pork',
  'citrus fruit',
  'pork',
  'pastry',
  'pork',
  'waffles',
  'other vegetables',
  'herbs',
  'pastry',
  'yogurt',
  'pork',
  'canned vegetables',
  'syrup',
  'cat food',
  'specialty cheese',
  'fruit/vegetable juice',
  'herbs',
  'long life bakery product'],
 ['pork',
  'curd',
  'chicken',
  'pickled vegetables',
  'other vegetables',
  'liquor (appetizer)',
  'curd',
  'onions',
  'hard cheese'],
 ['beef',
  'citrus fruit',
  'sausage',
  'napkins',
  'semi-finished bread',
  'other vegetables',
  'brown bread'],
 ['pastry',
  'bottled water',
  'sugar',
  'chicken',
  'sausage',
  'dishes',
  'whole milk',
  'whole milk',
  'whole milk',
  'bottled beer',
  'shopping bags',
  'canned beer'],
 ['canned beer',
  'pip fruit',
  'canned beer',
  'shopping bags',
  'frozen vegetables',
  'dessert',
  'long life bakery product',
  'dessert',
  'dish cleaner',
  'candy',
  'processed cheese',
  'canned vegetables'],
 ['root vegetables',
  'frankfurter',
  'whipped/sour cream',
  'meat',
  'specialty bar',
  'packaged fruit/vegetables',
  'misc. beverages',
  'other vegetables',
  'hygiene articles'],
 ['citrus fruit',
  'whole milk',
  'frankfurter',
  'ham',
  'pip fruit',
  'soft cheese',
  'red/blush wine',
  'soda',
  'whole milk',
  'rolls/buns',
  'other vegetables',
  'brown bread',
  'canned fish',
  'salty snack',
  'specialty chocolate',
  'whipped/sour cream',
  'yogurt'],
 ['sausage',
  'dessert',
  'ice cream',
  'cream cheese ',
  'butter',
  'meat',
  'specialty bar',
  'newspapers',
  'bottled beer',
  'rolls/buns',
  'soda',
  'yogurt',
  'frozen meals',
  'bottled water',
  'whipped/sour cream',
  'brown bread',
  'whipped/sour cream'],
 ['tropical fruit',
  'tropical fruit',
  'pork',
  'UHT-milk',
  'bottled beer',
  'cream cheese ',
  'beverages',
  'UHT-milk',
  'rice',
  'newspapers',
  'seasonal products',
  'newspapers',
  'butter milk',
  'bottled water'],
 ['berries',
  'frankfurter',
  'ham',
  'pork',
  'vinegar',
  'margarine',
  'specialty cheese',
  'whole milk',
  'yogurt',
  'other vegetables',
  'frozen vegetables',
  'butter',
  'UHT-milk',
  'brown bread',
  'newspapers',
  'domestic eggs',
  'brown bread'],
 ['canned beer',
  'other vegetables',
  'citrus fruit',
  'rolls/buns',
  'butter',
  'root vegetables',
  'hygiene articles',
  'rolls/buns',
  'dessert',
  'condensed milk',
  'fruit/vegetable juice',
  'bottled water',
  'seasonal products',
  'margarine',
  'baking powder',
  'fruit/vegetable juice',
  'skin care',
  'hygiene articles',
  'fruit/vegetable juice'],
 ['butter milk',
  'canned beer',
  'root vegetables',
  'yogurt',
  'semi-finished bread',
  'rolls/buns',
  'margarine'],
 ['coffee',
  'whole milk',
  'berries',
  'margarine',
  'soda',
  'napkins',
  'domestic eggs',
  'cat food',
  'other vegetables',
  'grapes',
  'whole milk',
  'cream cheese ',
  'other vegetables',
  'UHT-milk',
  'specialty chocolate',
  'soda',
  'whole milk',
  'margarine',
  'whole milk',
  'pastry',
  'other vegetables',
  'bottled water',
  'pastry',
  'meat spreads',
  'domestic eggs',
  'cat food',
  'pickled vegetables'],
 ['pastry',
  'meat',
  'citrus fruit',
  'soda',
  'other vegetables',
  'condensed milk',
  'UHT-milk',
  'tropical fruit',
  'rice',
  'other vegetables',
  'brown bread',
  'newspapers',
  'specialty bar',
  'tropical fruit',
  'white bread',
  'sugar',
  'chocolate marshmallow'],
 ['rolls/buns',
  'liver loaf',
  'margarine',
  'chicken',
  'other vegetables',
  'citrus fruit',
  'whipped/sour cream',
  'newspapers',
  'bottled water',
  'canned beer',
  'candy',
  'soda',
  'baking powder',
  'white wine'],
 ['misc. beverages',
  'tropical fruit',
  'root vegetables',
  'dish cleaner',
  'rolls/buns',
  'sausage',
  'pip fruit',
  'frozen vegetables',
  'other vegetables',
  'kitchen towels',
  'soda',
  'beverages',
  'butter',
  'other vegetables',
  'condensed milk'],
 ['root vegetables',
  'canned beer',
  'frozen fish',
  'pork',
  'brown bread',
  'soda',
  'bottled water',
  'coffee',
  'coffee',
  'pastry',
  'long life bakery product',
  'canned beer',
  'pastry'],
 ['sausage',
  'whole milk',
  'root vegetables',
  'berries',
  'other vegetables',
  'semi-finished bread',
  'shopping bags',
  'bottled beer',
  'yogurt'],
 ['canned beer',
  'pastry',
  'bottled water',
  'canned beer',
  'chicken',
  'root vegetables',
  'meat',
  'whole milk',
  'soda',
  'other vegetables',
  'domestic eggs',
  'cat food',
  'whole milk',
  'butter milk',
  'newspapers'],
 ['ham',
  'chewing gum',
  'sausage',
  'whole milk',
  'chicken',
  'meat',
  'pasta',
  'condensed milk',
  'other vegetables',
  'beverages',
  'hygiene articles',
  'other vegetables',
  'UHT-milk',
  'pot plants',
  'liquor',
  'frozen dessert',
  'whipped/sour cream',
  'sugar',
  'pip fruit'],
 ['turkey',
  'citrus fruit',
  'whole milk',
  'root vegetables',
  'whole milk',
  'sugar',
  'frozen meals',
  'yogurt',
  'cat food',
  'soda',
  'canned beer',
  'processed cheese',
  'other vegetables',
  'spread cheese',
  'canned fish'],
 ['whole milk',
  'tropical fruit',
  'soda',
  'whipped/sour cream',
  'beef',
  'beverages',
  'root vegetables',
  'Instant food products',
  'fruit/vegetable juice',
  'hard cheese',
  'chocolate',
  'dessert',
  'bottled beer',
  'margarine'],
 ['whole milk',
  'root vegetables',
  'chicken',
  'root vegetables',
  'specialty chocolate',
  'sausage',
  'sausage',
  'frozen vegetables',
  'whole milk',
  'frozen vegetables',
  'canned beer',
  'curd cheese',
  'snack products',
  'frozen fish',
  'chocolate'],
 ['packaged fruit/vegetables',
  'cereals',
  'ice cream',
  'chewing gum',
  'beef',
  'ham',
  'frozen vegetables',
  'yogurt',
  'condensed milk',
  'canned beer',
  'soda'],
 ['rolls/buns',
  'onions',
  'root vegetables',
  'beef',
  'bottled beer',
  'hamburger meat',
  'yogurt',
  'liquor',
  'pickled vegetables'],
 ['ham',
  'chicken',
  'other vegetables',
  'rolls/buns',
  'citrus fruit',
  'canned beer',
  'other vegetables',
  'cream cheese ',
  'flour',
  'other vegetables',
  'napkins'],
 ['rolls/buns',
  'canned vegetables',
  'canned beer',
  'candy',
  'chocolate marshmallow',
  'butter',
  'tropical fruit',
  'other vegetables',
  'chewing gum',
  'frozen meals',
  'yogurt',
  'long life bakery product',
  'margarine'],
 ['other vegetables',
  'frankfurter',
  'whole milk',
  'sausage',
  'whole milk',
  'other vegetables',
  'brown bread',
  'onions',
  'seasonal products',
  'grapes',
  'hard cheese',
  'soda',
  'fruit/vegetable juice',
  'waffles',
  'dental care'],
 ['sausage',
  'meat',
  'pork',
  'ham',
  'citrus fruit',
  'pastry',
  'butter',
  'other vegetables',
  'brown bread',
  'processed cheese',
  'specialty bar',
  'frozen fish',
  'canned beer',
  'salty snack'],
 ['sausage',
  'sausage',
  'pip fruit',
  'soda',
  'bottled beer',
  'frankfurter',
  'butter',
  'onions',
  'hygiene articles',
  'whole milk',
  'bottled water',
  'other vegetables',
  'chicken',
  'other vegetables',
  'ice cream',
  'soda'],
 ['frankfurter',
  'bottled beer',
  'whole milk',
  'beef',
  'grapes',
  'canned beer',
  'butter',
  'fruit/vegetable juice',
  'yogurt',
  'semi-finished bread'],
 ['rolls/buns',
  'pork',
  'tropical fruit',
  'onions',
  'yogurt',
  'butter',
  'yogurt',
  'tropical fruit',
  'whole milk',
  'soft cheese',
  'herbs',
  'rolls/buns',
  'rolls/buns'],
 ['whole milk',
  'pork',
  'domestic eggs',
  'frozen meals',
  'meat',
  'citrus fruit',
  'sausage',
  'other vegetables',
  'beef',
  'rolls/buns',
  'rolls/buns',
  'root vegetables',
  'coffee',
  'whipped/sour cream',
  'butter',
  'pot plants',
  'frozen meals',
  'long life bakery product',
  'whole milk',
  'sugar',
  'frozen vegetables',
  'fruit/vegetable juice',
  'frozen vegetables',
  'canned vegetables'],
 ['curd cheese',
  'meat',
  'other vegetables',
  'whole milk',
  'yogurt',
  'herbs',
  'bottled water',
  'fruit/vegetable juice',
  'mayonnaise',
  'tea',
  'zwieback'],
 ['red/blush wine',
  'bottled beer',
  'canned beer',
  'bottled beer',
  'curd cheese',
  'yogurt',
  'pip fruit',
  'brown bread',
  'whole milk',
  'red/blush wine',
  'bottled water',
  'mustard',
  'napkins',
  'margarine'],
 ['sausage',
  'whole milk',
  'berries',
  'whole milk',
  'pastry',
  'tropical fruit',
  'whole milk',
  'tropical fruit',
  'seasonal products',
  'misc. beverages',
  'hygiene articles',
  'soda',
  'berries',
  'long life bakery product',
  'dish cleaner',
  'specialty bar',
  'domestic eggs',
  'yogurt',
  'fruit/vegetable juice',
  'soda',
  'coffee',
  'bottled water'],
 ['tropical fruit', 'yogurt', 'pip fruit', 'yogurt', 'yogurt'],
 ['red/blush wine',
  'canned beer',
  'root vegetables',
  'sausage',
  'soft cheese',
  'whole milk',
  'dessert',
  'other vegetables',
  'other vegetables',
  'soda',
  'other vegetables',
  'yogurt',
  'whole milk',
  'bottled water',
  'soda',
  'pastry',
  'whole milk',
  'canned beer',
  'yogurt',
  'bottled water',
  'rolls/buns'],
 ['whole milk',
  'root vegetables',
  'specialty chocolate',
  'bottled beer',
  'frankfurter',
  'soda',
  'bottled beer',
  'newspapers',
  'canned beer',
  'margarine',
  'shopping bags',
  'soda',
  'bottled water',
  'oil',
  'domestic eggs',
  'rolls/buns',
  'shopping bags'],
 ['frankfurter',
  'misc. beverages',
  'butter',
  'zwieback',
  'other vegetables',
  'whole milk',
  'margarine',
  'liquor',
  'newspapers',
  'bottled water',
  'bottled water'],
 ['whole milk',
  'frozen vegetables',
  'rolls/buns',
  'bottled beer',
  'specialty cheese',
  'domestic eggs',
  'chewing gum'],
 ['frozen potato products',
  'citrus fruit',
  'flour',
  'pastry',
  'tropical fruit',
  'bottled water',
  'frankfurter',
  'grapes',
  'frankfurter',
  'bottled beer',
  'pip fruit',
  'rolls/buns',
  'brown bread',
  'cream cheese ',
  'citrus fruit',
  'red/blush wine',
  'dessert',
  'whole milk',
  'roll products ',
  'grapes',
  'other vegetables',
  'cat food',
  'chocolate',
  'bottled beer',
  'pickled vegetables',
  'misc. beverages',
  'frozen vegetables',
  'detergent',
  'salt'],
 ['other vegetables',
  'whole milk',
  'yogurt',
  'curd',
  'rolls/buns',
  'hygiene articles',
  'yogurt',
  'hard cheese',
  'shopping bags',
  'margarine',
  'frozen vegetables',
  'skin care',
  'bottled beer'],
 ['citrus fruit',
  'root vegetables',
  'tropical fruit',
  'frankfurter',
  'yogurt',
  'bottled water',
  'salty snack',
  'white bread',
  'processed cheese',
  'newspapers',
  'canned beer',
  'yogurt',
  'white wine',
  'beverages'],
 ['flour',
  'yogurt',
  'pork',
  'pork',
  'yogurt',
  'butter',
  'whipped/sour cream',
  'shopping bags',
  'whipped/sour cream',
  'brown bread',
  'hard cheese'],
 ['sugar',
  'beverages',
  'rolls/buns',
  'canned vegetables',
  'whole milk',
  'grapes',
  'flour',
  'sausage',
  'white bread',
  'bottled water',
  'popcorn',
  'rolls/buns',
  'salty snack'],
 ['frozen meals',
  'canned beer',
  'canned beer',
  'whole milk',
  'chicken',
  'frankfurter',
  'whipped/sour cream',
  'white bread',
  'whole milk',
  'domestic eggs',
  'whole milk',
  'flour',
  'flour',
  'bottled beer',
  'sugar'],
 ['chocolate',
  'newspapers',
  'pork',
  'pip fruit',
  'soda',
  'citrus fruit',
  'oil',
  'rolls/buns',
  'whole milk',
  'white bread',
  'other vegetables',
  'grapes',
  'bottled water',
  'UHT-milk',
  'waffles',
  'frozen vegetables'],
 ['root vegetables',
  'finished products',
  'fruit/vegetable juice',
  'sausage',
  'specialty vegetables',
  'cream cheese ',
  'other vegetables',
  'root vegetables',
  'curd',
  'yogurt',
  'UHT-milk',
  'pastry'],
 ['root vegetables',
  'rolls/buns',
  'whole milk',
  'newspapers',
  'whole milk',
  'liquor',
  'packaged fruit/vegetables',
  'frozen vegetables',
  'whole milk',
  'whole milk',
  'domestic eggs',
  'specialty chocolate',
  'hygiene articles',
  'shopping bags',
  'whipped/sour cream',
  'seasonal products',
  'domestic eggs',
  'softener'],
 ['herbs',
  'frankfurter',
  'sausage',
  'rolls/buns',
  'pork',
  'fruit/vegetable juice',
  'beef',
  'cat food',
  'curd cheese',
  'sugar',
  'hard cheese',
  'white wine',
  'other vegetables',
  'hard cheese',
  'whole milk',
  'other vegetables',
  'yogurt',
  'newspapers',
  'soft cheese',
  'rolls/buns',
  'long life bakery product',
  'UHT-milk',
  'candy'],
 ['bottled water',
  'butter',
  'yogurt',
  'chicken',
  'processed cheese',
  'whipped/sour cream',
  'whole milk',
  'whole milk',
  'fruit/vegetable juice',
  'rolls/buns',
  'frozen vegetables'],
 ['sausage',
  'bottled beer',
  'coffee',
  'whole milk',
  'turkey',
  'sausage',
  'pip fruit',
  'herbs',
  'tropical fruit',
  'grapes',
  'packaged fruit/vegetables',
  'spread cheese',
  'chocolate',
  'frozen vegetables'],
 ['coffee',
  'root vegetables',
  'fish',
  'mayonnaise',
  'other vegetables',
  'sausage',

In [99]:
te=TransactionEncoder()
te.fit(market)

TransactionEncoder()

In [100]:
a=te.transform(market)
data=pd.DataFrame(a,columns=te.columns_)
data

      Instant food products  UHT-milk  ...  yogurt  zwieback
0                     False     False  ...   False     False
1                     False     False  ...   False     False
2                     False     False  ...   False     False
3                     False     False  ...   False     False
4                     False     False  ...   False     False
...                     ...       ...  ...     ...       ...
3893                  False     False  ...   False     False
3894                  False     False  ...    True     False
3895                  False     False  ...   False     False
3896                  False     False  ...   False     False
3897                  False     False  ...   False     False

[3898 rows x 167 columns]

In [102]:
apriori(data,min_support=0.05,use_colnames=True).sort_values(by="support",ascending=False)

      support                                        itemsets
55   0.458184                                    (whole milk)
37   0.376603                              (other vegetables)
41   0.349666                                    (rolls/buns)
47   0.313494                                          (soda)
56   0.282966                                        (yogurt)
51   0.233710                                (tropical fruit)
42   0.230631                               (root vegetables)
5    0.213699                                 (bottled water)
44   0.206003                                       (sausage)
116  0.191380                  (whole milk, other vegetables)
13   0.185480                                  (citrus fruit)
133  0.178553                        (whole milk, rolls/buns)
38   0.177527                                        (pastry)
39   0.170600                                     (pip fruit)
45   0.168291                                 (shopping bags)
10   0.165213                                   (canned beer)
4    0.158799                                  (bottled beer)
53   0.154695                            (whipped/sour cream)
148  0.151103                              (whole milk, soda)
153  0.150590                            (whole milk, yogurt)
109  0.146742                  (rolls/buns, other vegetables)
34   0.139815                                    (newspapers)
19   0.137506                                   (frankfurter)
6    0.135967                                   (brown bread)
18   0.133145                                 (domestic eggs)
40   0.132376                                          (pork)
7    0.126475                                        (butter)
22   0.124936                         (fruit/vegetable juice)
113  0.124166                        (soda, other vegetables)
16   0.120831                                          (curd)
117  0.120318                      (yogurt, other vegetables)
130  0.119805                              (rolls/buns, soda)
1    0.119548                                          (beef)
30   0.116983                                     (margarine)
150  0.116470                    (whole milk, tropical fruit)
14   0.114931                                        (coffee)
138  0.113135                   (whole milk, root vegetables)
68   0.112365                     (whole milk, bottled water)
134  0.111339                            (yogurt, rolls/buns)
142  0.106978                           (whole milk, sausage)
21   0.102617                             (frozen vegetables)
11   0.100564                                       (chicken)
149  0.097486                                  (yogurt, soda)
110  0.094151             (other vegetables, root vegetables)
63   0.093894               (bottled water, other vegetables)
111  0.092868                     (sausage, other vegetables)
84   0.092355                      (whole milk, citrus fruit)
145  0.091329                     (whole milk, shopping bags)
114  0.091329              (tropical fruit, other vegetables)
120  0.091072                            (whole milk, pastry)
127  0.090816                   (rolls/buns, root vegetables)
54   0.088763                                   (white bread)
15   0.088507                                 (cream cheese )
131  0.088250                    (tropical fruit, rolls/buns)
78   0.087224                       (whole milk, canned beer)
124  0.086968                         (whole milk, pip fruit)
17   0.086455                                       (dessert)
12   0.086455                                     (chocolate)
62   0.085428                      (bottled beer, whole milk)
128  0.082350                           (rolls/buns, sausage)
156  0.082093      (whole milk, rolls/buns, other vegetables)
147  0.081837                          (tropical fruit, soda)
33   0.081324                                       (napkins)
136  0.081324                         (soda, root vegetables)
25   0.080298                                (hamburger meat)
152  0.079785                (whole milk, whipped/sour cream)
2    0.079785                                       (berries)
64   0.079271                     (bottled water, rolls/buns)
0    0.078502                                      (UHT-milk)
81   0.077476                (citrus fruit, other vegetables)
140  0.077219                                 (sausage, soda)
66   0.076193                           (bottled water, soda)
36   0.076193                                        (onions)
151  0.075680                        (tropical fruit, yogurt)
143  0.075423                               (yogurt, sausage)
112  0.073114               (other vegetables, shopping bags)
107  0.072345                   (other vegetables, pip fruit)
105  0.072345                        (whole milk, newspapers)
82   0.071832                      (rolls/buns, citrus fruit)
161  0.071832          (whole milk, yogurt, other vegetables)
139  0.071575                       (yogurt, root vegetables)
106  0.071575                      (pastry, other vegetables)
92   0.070292                     (whole milk, domestic eggs)
72   0.069779                       (whole milk, brown bread)
118  0.069523                            (rolls/buns, pastry)
159  0.069266            (whole milk, soda, other vegetables)
43   0.069266                                   (salty snack)
52   0.069010                                       (waffles)
129  0.068753                     (rolls/buns, shopping bags)
59   0.068497                (bottled beer, other vegetables)
96   0.067984                       (frankfurter, whole milk)
122  0.067214                         (rolls/buns, pip fruit)
75   0.067214                 (canned beer, other vegetables)
115  0.066957          (whipped/sour cream, other vegetables)
126  0.066957                              (whole milk, pork)
76   0.066701                       (canned beer, rolls/buns)
69   0.066444                         (yogurt, bottled water)
74   0.066188                            (whole milk, butter)
50   0.065931                                         (sugar)
163  0.065931                (whole milk, rolls/buns, yogurt)
29   0.065418                      (long life bakery product)
162  0.065162                  (whole milk, rolls/buns, soda)
83   0.065162                            (citrus fruit, soda)
8    0.064905                                   (butter milk)
144  0.064649                           (soda, shopping bags)
58   0.064135                              (whole milk, beef)
89   0.063622                              (curd, whole milk)
31   0.063622                                          (meat)
24   0.063366                                           (ham)
60   0.063109                      (bottled beer, rolls/buns)
119  0.063109                                  (pastry, soda)
20   0.062853                                  (frozen meals)
100  0.062340             (whole milk, fruit/vegetable juice)
3    0.062083                                     (beverages)
93   0.061057                 (frankfurter, other vegetables)
123  0.060544                               (soda, pip fruit)
70   0.059774                 (brown bread, other vegetables)
102  0.059518                         (whole milk, margarine)
32   0.059005                               (misc. beverages)
49   0.058492                           (specialty chocolate)
132  0.058492                (whipped/sour cream, rolls/buns)
85   0.058235                          (yogurt, citrus fruit)
121  0.057978                                (yogurt, pastry)
137  0.057465               (tropical fruit, root vegetables)
73   0.057209                      (other vegetables, butter)
104  0.057209                        (rolls/buns, newspapers)
125  0.056696                             (yogurt, pip fruit)
67   0.056439                 (tropical fruit, bottled water)
28   0.056439                                     (ice cream)
135  0.056183                      (sausage, root vegetables)
154  0.056183   (whole milk, bottled water, other vegetables)
35   0.055670                                           (oil)
108  0.055670                        (pork, other vegetables)
86   0.055156                            (whole milk, coffee)
94   0.055156                       (frankfurter, rolls/buns)
61   0.055156                            (bottled beer, soda)
97   0.055156                 (whole milk, frozen vegetables)
146  0.054900                         (yogurt, shopping bags)
23   0.054900                                        (grapes)
77   0.054643                             (canned beer, soda)
141  0.054643                       (tropical fruit, sausage)
90   0.054387               (domestic eggs, other vegetables)
164  0.054387                      (whole milk, soda, yogurt)
65   0.054130                (bottled water, root vegetables)
9    0.053874                                         (candy)
99   0.053617             (rolls/buns, fruit/vegetable juice)
26   0.053361                                   (hard cheese)
71   0.053361                       (rolls/buns, brown bread)
91   0.052591                     (rolls/buns, domestic eggs)
155  0.052591            (rolls/buns, soda, other vegetables)
48   0.052591                                 (specialty bar)
98   0.052591       (other vegetables, fruit/vegetable juice)
27   0.052335                              (hygiene articles)
157  0.052335          (yogurt, rolls/buns, other vegetables)
46   0.051821                                 (sliced cheese)
79   0.051821                           (canned beer, yogurt)
87   0.051565                        (curd, other vegetables)
103  0.051565                  (newspapers, other vegetables)
95   0.051052                             (frankfurter, soda)
57   0.050795                        (beef, other vegetables)
160  0.050539  (whole milk, tropical fruit, other vegetables)
158  0.050282         (whole milk, sausage, other vegetables)
80   0.050026                           (whole milk, chicken)
88   0.050026                              (curd, rolls/buns)
101  0.050026                   (margarine, other vegetables)