In [6]:
import pandas as pd
from mlxtend.preprocessing.transactionencoder import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth

In [8]:
df=pd.read_csv("Groceries_dataset.csv")
df.head(10)

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk
5           4941  14-02-2015        rolls/buns
6           4501  08-05-2015  other vegetables
7           3803  23-12-2015        pot plants
8           2762  20-03-2015        whole milk
9           4119  12-02-2015    tropical fruit

In [ ]:
gp=df.groupby(["itemDescription"]).agg({"itemDescription":"count"})
gp.rename(columns={"itemDescription": "CountOfItemDescription"}, inplace=True)
gp.sort_values(by="CountOfItemDescription",ascending=False)

In [17]:
d:dict[int:list]={}
for _,row in df.iterrows():
    key=row[0]
    value=row[2]
    if key not in d:
        d[key]=[]
    d[key].append(value)
market=[]
for i in d.values():
    market.append(i)
del d

C:\Users\mitad\AppData\Local\Temp\ipykernel_27176\189042124.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  key=row[0]
C:\Users\mitad\AppData\Local\Temp\ipykernel_27176\189042124.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  value=row[2]

In [ ]:
te=TransactionEncoder()
a=te.fit_transform(market)
data=pd.DataFrame(a,columns=te.columns_)
data

In [22]:
fpgrowth(data,min_support=0.05,use_colnames=True).sort_values(by="support",ascending=False)

      support                                        itemsets
0    0.458184                                    (whole milk)
9    0.376603                              (other vegetables)
1    0.349666                                    (rolls/buns)
21   0.313494                                          (soda)
26   0.282966                                        (yogurt)
2    0.233710                                (tropical fruit)
10   0.230631                               (root vegetables)
33   0.213699                                 (bottled water)
16   0.206003                                       (sausage)
71   0.191380                  (whole milk, other vegetables)
3    0.185480                                  (citrus fruit)
57   0.178553                        (rolls/buns, whole milk)
39   0.177527                                        (pastry)
17   0.170600                                     (pip fruit)
11   0.168291                                 (shopping bags)
27   0.165213                                   (canned beer)
28   0.158799                                  (bottled beer)
38   0.154695                            (whipped/sour cream)
109  0.151103                              (soda, whole milk)
117  0.150590                            (whole milk, yogurt)
58   0.146742                  (rolls/buns, other vegetables)
29   0.139815                                    (newspapers)
18   0.137506                                   (frankfurter)
34   0.135967                                   (brown bread)
22   0.133145                                 (domestic eggs)
19   0.132376                                          (pork)
12   0.126475                                        (butter)
20   0.124936                         (fruit/vegetable juice)
108  0.124166                        (soda, other vegetables)
50   0.120831                                          (curd)
120  0.120318                      (yogurt, other vegetables)
110  0.119805                              (rolls/buns, soda)
40   0.119548                                          (beef)
48   0.116983                                     (margarine)
60   0.116470                    (tropical fruit, whole milk)
13   0.114931                                        (coffee)
72   0.113135                   (whole milk, root vegetables)
140  0.112365                     (whole milk, bottled water)
118  0.111339                            (rolls/buns, yogurt)
90   0.106978                           (whole milk, sausage)
42   0.102617                             (frozen vegetables)
35   0.100564                                       (chicken)
119  0.097486                                  (soda, yogurt)
73   0.094151             (root vegetables, other vegetables)
137  0.093894               (bottled water, other vegetables)
86   0.092868                     (sausage, other vegetables)
66   0.092355                      (citrus fruit, whole milk)
78   0.091329                     (whole milk, shopping bags)
62   0.091329              (tropical fruit, other vegetables)
152  0.091072                            (pastry, whole milk)
75   0.090816                   (rolls/buns, root vegetables)
24   0.088763                                   (white bread)
43   0.088507                                 (cream cheese )
61   0.088250                    (rolls/buns, tropical fruit)
125  0.087224                       (whole milk, canned beer)
96   0.086968                         (whole milk, pip fruit)
36   0.086455                                       (dessert)
14   0.086455                                     (chocolate)
130  0.085428                      (whole milk, bottled beer)
87   0.082350                           (rolls/buns, sausage)
59   0.082093      (rolls/buns, whole milk, other vegetables)
63   0.081837                          (soda, tropical fruit)
76   0.081324                         (soda, root vegetables)
4    0.081324                                       (napkins)
30   0.080298                                (hamburger meat)
151  0.079785                (whipped/sour cream, whole milk)
37   0.079785                                       (berries)
141  0.079271                     (rolls/buns, bottled water)
51   0.078502                                      (UHT-milk)
68   0.077476                (citrus fruit, other vegetables)
92   0.077219                                 (soda, sausage)
23   0.076193                                        (onions)
138  0.076193                           (soda, bottled water)
64   0.075680                        (tropical fruit, yogurt)
91   0.075423                               (sausage, yogurt)
79   0.073114               (shopping bags, other vegetables)
94   0.072345                   (pip fruit, other vegetables)
134  0.072345                        (whole milk, newspapers)
67   0.071832                      (rolls/buns, citrus fruit)
124  0.071832          (whole milk, yogurt, other vegetables)
77   0.071575                       (root vegetables, yogurt)
156  0.071575                      (pastry, other vegetables)
115  0.070292                     (whole milk, domestic eggs)
146  0.069779                       (brown bread, whole milk)
153  0.069523                            (pastry, rolls/buns)
111  0.069266            (soda, whole milk, other vegetables)
31   0.069266                                   (salty snack)
44   0.069010                                       (waffles)
81   0.068753                     (rolls/buns, shopping bags)
133  0.068497                (bottled beer, other vegetables)
101  0.067984                       (whole milk, frankfurter)
129  0.067214                 (canned beer, other vegetables)
95   0.067214                         (rolls/buns, pip fruit)
104  0.066957                              (pork, whole milk)
149  0.066957          (whipped/sour cream, other vegetables)
126  0.066701                       (rolls/buns, canned beer)
142  0.066444                         (bottled water, yogurt)
83   0.066188                            (whole milk, butter)
121  0.065931                (rolls/buns, whole milk, yogurt)
5    0.065931                                         (sugar)
6    0.065418                      (long life bakery product)
112  0.065162                  (rolls/buns, soda, whole milk)
69   0.065162                            (soda, citrus fruit)
32   0.064905                                   (butter milk)
80   0.064649                           (soda, shopping bags)
157  0.064135                              (beef, whole milk)
164  0.063622                              (curd, whole milk)
7    0.063622                                          (meat)
25   0.063366                                           (ham)
154  0.063109                                  (pastry, soda)
131  0.063109                      (rolls/buns, bottled beer)
52   0.062853                                  (frozen meals)
106  0.062340             (whole milk, fruit/vegetable juice)
47   0.062083                                     (beverages)
99   0.061057                 (frankfurter, other vegetables)
97   0.060544                               (soda, pip fruit)
145  0.059774                 (brown bread, other vegetables)
161  0.059518                         (margarine, whole milk)
54   0.059005                               (misc. beverages)
150  0.058492                (rolls/buns, whipped/sour cream)
45   0.058492                           (specialty chocolate)
70   0.058235                          (citrus fruit, yogurt)
155  0.057978                                (pastry, yogurt)
74   0.057465               (tropical fruit, root vegetables)
135  0.057209                        (rolls/buns, newspapers)
84   0.057209                      (butter, other vegetables)
98   0.056696                             (pip fruit, yogurt)
55   0.056439                                     (ice cream)
139  0.056439                 (tropical fruit, bottled water)
144  0.056183   (whole milk, bottled water, other vegetables)
88   0.056183                      (root vegetables, sausage)
49   0.055670                                           (oil)
103  0.055670                        (pork, other vegetables)
159  0.055156                 (whole milk, frozen vegetables)
132  0.055156                            (soda, bottled beer)
102  0.055156                       (rolls/buns, frankfurter)
85   0.055156                            (whole milk, coffee)
56   0.054900                                        (grapes)
82   0.054900                         (yogurt, shopping bags)
89   0.054643                       (tropical fruit, sausage)
127  0.054643                             (soda, canned beer)
123  0.054387                      (soda, whole milk, yogurt)
114  0.054387               (domestic eggs, other vegetables)
143  0.054130                (root vegetables, bottled water)
8    0.053874                                         (candy)
107  0.053617             (rolls/buns, fruit/vegetable juice)
147  0.053361                       (rolls/buns, brown bread)
53   0.053361                                   (hard cheese)
41   0.052591                                 (specialty bar)
113  0.052591            (rolls/buns, soda, other vegetables)
105  0.052591       (fruit/vegetable juice, other vegetables)
116  0.052591                     (rolls/buns, domestic eggs)
15   0.052335                              (hygiene articles)
122  0.052335          (rolls/buns, yogurt, other vegetables)
128  0.051821                           (canned beer, yogurt)
46   0.051821                                 (sliced cheese)
162  0.051565                        (curd, other vegetables)
136  0.051565                  (newspapers, other vegetables)
100  0.051052                             (soda, frankfurter)
158  0.050795                        (beef, other vegetables)
65   0.050539  (tropical fruit, whole milk, other vegetables)
93   0.050282         (whole milk, sausage, other vegetables)
148  0.050026                           (whole milk, chicken)
160  0.050026                   (margarine, other vegetables)
163  0.050026                              (curd, rolls/buns)